#!/bin/sh
#
# @name ASV Roboato (Gazebo)
#
# @type Surface Boat
# @class Rover
#
# @output Motor1 port thruster
# @output Motor2 starboard thruster
#

. ${R}/etc/init.d/rc.boat_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=xroboato}

param set-default SIM_GZ_EN 1

# SITL simulated sensors
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Control allocation: 2 differential thrusters
param set-default CA_AIRFRAME 9
param set-default CA_ROTOR_COUNT 2
param set-default CA_R_REV 3

# Thruster 0: port (rear-left)
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -0.5
param set-default CA_ROTOR0_PY -0.49

# Thruster 1: starboard (rear-right)
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX -0.5
param set-default CA_ROTOR1_PY 0.49

# Heron-scale speed/steering (GND_WHEEL_BASE = pontoon separation)
param set-default GND_L1_DIST 5
param set-default GND_L1_PERIOD 30
param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_I 3
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_P 2
param set-default GND_SPEED_THR_SC 1
param set-default GND_SPEED_TRIM 1
param set-default GND_THR_CRUISE 0.6
param set-default GND_THR_MAX 1
param set-default GND_THR_MIN 0
param set-default GND_MAX_ANG 0.6
param set-default GND_WHEEL_BASE 0.98

param set-default NAV_ACC_RAD 2
param set-default NAV_LOITER_RAD 3

# Gazebo simulated ESC outputs
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0

param set-default SIM_GZ_EC_MAX1 1900
param set-default SIM_GZ_EC_MAX2 1900
