#!/bin/sh
#
# @name AUV UDrone (Gazebo)
#
# @type Underwater Robot
# @class Underwater Robot
#
# @output Motor1 T200 CCW, starboard-bottom
# @output Motor2 T200 CCW, port-bottom
# @output Motor3 T200 CW,  port-top
# @output Motor4 T200 CW,  starboard-top
#

# Source UUV defaults (MAV_TYPE 12 submarine, EKF2 EV fusion, etc.)
. ${R}/etc/init.d/rc.uuv_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=underwater}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=xudrone}

param set-default SIM_GZ_EN 1

# SITL simulated sensor enables
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Cube 2.1-style: disable ESC checks (thrusters, not ESCs)
param set-default COM_ARM_CHK_ESCS 0
param set-default FD_ESCS_EN 0

# Control allocation: UUV airframe
param set-default CA_AIRFRAME 7
param set-default CA_METHOD 0
param set-default MAV_TYPE 12

# 12V 30Ah LiFePO4 battery (4S, 3.2 V/cell nominal)
param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 30000
param set-default BAT1_V_CHARGED 3.6
param set-default BAT1_V_EMPTY 2.5

# Failsafes appropriate for underwater
param set-default COM_ACT_FAIL_ACT 0
param set-default COM_LOW_BAT_ACT 0
param set-default NAV_DLL_ACT 0
param set-default GF_ACTION 1
param set-default NAV_RCL_ACT 1

# Disable attitude failure detection
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0

# ------------------------------------------------------------------
# 4× Blue Robotics T200 thrusters at rear corners
# Hull: 17 in long × 10 in dia, 13 kg total
# All thrust along +X (forward), positions relative to CG at origin
# ------------------------------------------------------------------
param set-default CA_ROTOR_COUNT 4
param set-default CA_R_REV 255

# T200 #0: starboard-bottom  (Y=-0.15, Z=-0.15)
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -0.26
param set-default CA_ROTOR0_PY -0.15
param set-default CA_ROTOR0_PZ -0.15

# T200 #1: port-bottom  (Y=0.15, Z=-0.15)
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX -0.26
param set-default CA_ROTOR1_PY 0.15
param set-default CA_ROTOR1_PZ -0.15

# T200 #2: port-top  (Y=0.15, Z=0.15)
param set-default CA_ROTOR2_AX 1
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX -0.26
param set-default CA_ROTOR2_PY 0.15
param set-default CA_ROTOR2_PZ 0.15

# T200 #3: starboard-top  (Y=-0.15, Z=0.15)
param set-default CA_ROTOR3_AX 1
param set-default CA_ROTOR3_AY 0
param set-default CA_ROTOR3_AZ 0
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX -0.26
param set-default CA_ROTOR3_PY -0.15
param set-default CA_ROTOR3_PZ 0.15

# Gazebo simulated ESC outputs
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 1100
param set-default SIM_GZ_EC_MIN2 1100
param set-default SIM_GZ_EC_MIN3 1100
param set-default SIM_GZ_EC_MIN4 1100

param set-default SIM_GZ_EC_MAX1 1900
param set-default SIM_GZ_EC_MAX2 1900
param set-default SIM_GZ_EC_MAX3 1900
param set-default SIM_GZ_EC_MAX4 1900
